# Welcome to Agency Jekyll Theme!

# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings

title: outbreak science
email: info@outbreakscience.org
description: > # this means to ignore newlines until "author:"
  Outbreak Science is a nonprofit aiming to advance the science of outbreak response by supporting open data, open access, and open science.
author: Outbreak Science
keyword: outbreak, epidemic, pandemic, science, research, open, health
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://outbreakscience.org" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  outbreaksci

# Build settings
markdown: kramdown

#theme: agency-jekyll-theme #The "agency-jekyll-theme" is not supported by GitHub Pages.

gems:
  - jekyll-feed
exclude:
  - agency-jekyll-theme.gemspec
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
